spring.application.name=adeem

spring.datasource.url=jdbc:postgresql://localhost:5432/adeem_db
spring.datasource.username=adeem_user
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true