spring.application.name=adeem

spring.datasource.url=jdbc:postgresql://localhost:5432/adeem_db
spring.datasource.username=adeem_user
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY_AT_LEAST_256_BITS
jwt.expiration=86400000

claude.api.key=${CLAUDE_API_KEY}
#claude.api.model=claude-sonnet-4-20250514